# Copyright 2024 Google LLC
# proto-file: system/software_defined_vehicle/core_services/orchestration/src/distributed_config/protos/vm_config.proto
# proto-message: VmConfig

# Publishes vehicle data on SDV data tunnel topics.
service_instances {
  config_alias: "HarSdvVehicleDataPublisher"
  instance_name: "instance-1"
  service_name: "com.sdv.google.display_safety.vehicle_data.publisher"
  package_name: "com.sdv.google.display_safety"
  vm_name: "vm-sdv"
}

# Produces a demo sequence of fake data and requests HarSdvVehicleDataPublisher
# to publish them on SDV Data tunnel topics.
service_instances {
  config_alias: "HarSdvFakeVehicleDataPublisherServiceBundle"
  instance_name: "instance-1"
  service_name: "com.sdv.google.display_safety.fake_vehicle_data.publisher"
  package_name: "com.sdv.google.display_safety"
  vm_name: "vm-sdv"
}

# HAR-SDV service bundle implements all integrations for Harry.
service_instances {
  config_alias: "HarSdvServiceBundle"
  instance_name: "instance-1"
  service_name: "com.sdv.google.display_safety.har_sdv_service"
  package_name: "com.sdv.google.display_safety"
  vm_name: "vm-sdv"
}