// Copyright 2025 Google LLC

//! WARNING: DO NOT EDIT.
//! WARNING: This file is generated by VSIDL middleware code generator.
//! WARNING: Changes will be overwritten when the file is regenerated.

pub mod internal {
    //! Those are internal symbols utilized by the middleware. Please refrain from using them.

    /// Default unit name for of a service unit implementing DriverUIService interface
    pub const DEFAULT_UNIT_NAME: &str = "com-sdv-google-display-safety-driver-ui-service";

    /// Creates a method map for an object which implements the RPC interface trait
    pub fn get_method_map(
        server: std::sync::Arc<dyn super::Interface>,
    ) -> std::collections::HashMap<String, sdv::comms::rpc::UnaryRpcMethod> {
        sdv::mw::MethodMapBuilder::new()
        .add_method::<oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatRequest, oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatResponse>(
            "Heartbeat",
            {
                let srv = server.clone();
            std::sync::Arc::new(move |id, req| {
                Box::pin({
                    let srv = srv.clone();
                    async move { srv.Heartbeat(id, &req).await }
                })
            })},
        )
        .add_method::<oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedRequest, oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedResponse>(
            "DocumentSwitched",
            {
                let srv = server.clone();
            std::sync::Arc::new(move |id, req| {
                Box::pin({
                    let srv = srv.clone();
                    async move { srv.DocumentSwitched(id, &req).await }
                })
            })},
        )
        .add_method::<oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedRequest, oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedResponse>(
            "DocumentUpdated",
            {
                let srv = server.clone();
            std::sync::Arc::new(move |id, req| {
                Box::pin({
                    let srv = srv.clone();
                    async move { srv.DocumentUpdated(id, &req).await }
                })
            })},
        )
        .add_method::<oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateRequest, oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateResponse>(
            "DesignTokenUpdate",
            {
                let srv = server.clone();
            std::sync::Arc::new(move |id, req| {
                Box::pin({
                    let srv = srv.clone();
                    async move { srv.DesignTokenUpdate(id, &req).await }
                })
            })},
        )
        .add_method::<oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateRequest, oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateResponse>(
            "LocaleUpdate",
            {
                let srv = server.clone();
            std::sync::Arc::new(move |id, req| {
                Box::pin({
                    let srv = srv.clone();
                    async move { srv.LocaleUpdate(id, &req).await }
                })
            })},
        ).build()
    }
}

#[allow(non_snake_case, missing_docs)]
#[async_trait::async_trait]
/// DriverUIService RPC server interface trait
pub trait Interface: Send + Sync {
    async fn Heartbeat(
        &self,
        _caller_id: sdv::comms::id::ServiceFqin,
        _request: &oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatRequest,
    ) -> sdv::status::SdvResult<oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatResponse>
    {
        Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Unimplemented))
    }
    async fn DocumentSwitched(
        &self,
        _caller_id: sdv::comms::id::ServiceFqin,
        _request: &oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedResponse,
    > {
        Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Unimplemented))
    }
    async fn DocumentUpdated(
        &self,
        _caller_id: sdv::comms::id::ServiceFqin,
        _request: &oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedResponse,
    > {
        Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Unimplemented))
    }
    async fn DesignTokenUpdate(
        &self,
        _caller_id: sdv::comms::id::ServiceFqin,
        _request: &oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateResponse,
    > {
        Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Unimplemented))
    }
    async fn LocaleUpdate(
        &self,
        _caller_id: sdv::comms::id::ServiceFqin,
        _request: &oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateRequest,
    ) -> sdv::status::SdvResult<oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateResponse>
    {
        Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Unimplemented))
    }
}

/// Client for DriverUIService RPC interface
pub struct Client(Box<dyn sdv::mw::ClientTransport>);

#[allow(non_snake_case, missing_docs)]
impl Client {
    pub async fn Heartbeat(
        &self,
        request: &oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatRequest,
    ) -> sdv::status::SdvResult<oem_harry_vehicle_messages_catalog_v1::driverui::HeartbeatResponse>
    {
        sdv::mw::call_method(self.0.as_ref(), "Heartbeat", request).await
    }
    pub async fn DocumentSwitched(
        &self,
        request: &oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DocumentSwitchedResponse,
    > {
        sdv::mw::call_method(self.0.as_ref(), "DocumentSwitched", request).await
    }
    pub async fn DocumentUpdated(
        &self,
        request: &oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DocumentUpdatedResponse,
    > {
        sdv::mw::call_method(self.0.as_ref(), "DocumentUpdated", request).await
    }
    pub async fn DesignTokenUpdate(
        &self,
        request: &oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateRequest,
    ) -> sdv::status::SdvResult<
        oem_harry_vehicle_messages_catalog_v1::driverui::DesignTokenUpdateResponse,
    > {
        sdv::mw::call_method(self.0.as_ref(), "DesignTokenUpdate", request).await
    }
    pub async fn LocaleUpdate(
        &self,
        request: &oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateRequest,
    ) -> sdv::status::SdvResult<oem_harry_vehicle_messages_catalog_v1::driverui::LocaleUpdateResponse>
    {
        sdv::mw::call_method(self.0.as_ref(), "LocaleUpdate", request).await
    }
}

impl sdv::mw::RpcClient for Client {
    /// Default unit name for the RPC
    const DEFAULT_UNIT_NAME: &'static str = internal::DEFAULT_UNIT_NAME;
    /// Create a client
    fn new(transport: Box<dyn sdv::mw::ClientTransport>) -> Self {
        Self(transport)
    }
}
