// Copyright 2023 Google LLC

syntax = "proto3";

package har.vehicledata;

import "syntax/vsidl.proto";

// TODO: figure out how to create topic without an enum
enum VehicleSpeedTopic {
    option (sdv.vsidl.is_topic) = true;
    VEHICLE_SPEED = 0;
    MAX_SPEED = 1;
    SPEEDLIMIT = 2;
}

message VehicleSpeed {
    option (sdv.vsidl.topic) = {
        typed_name: "VehicleSpeedTopic"
    };
    uint32 speed = 1;
}

// Alert type telltales
enum Telltale {
  option (sdv.vsidl.is_topic) = true;
    OIL_PRESSURE = 0;
    ENGINE_TEMP = 1;
    CHECK_ENGINE = 2;
    CHARGING_FAILURE = 3;
    SEATBELT_DRIVER = 4;
    SEATBELT_PASSENGER = 5;
    LOW_TIRE_PRESSURE = 6;
    AIRBAG = 7;
    ABS = 8;
    BRAKE = 9;
    TRACTION = 10;
    FOG_LIGHTS = 11;
    PARK_LIGHTS = 12;
    HIBEAM = 13;
    LOWBEAM = 14;
    TURN_SIGNAL_LEFT = 15;
    TURN_SIGNAL_RIGHT = 16;
    ADAS = 17;
    MAX_SPEED_DISPLAYED = 18;
    SPEED_LIMIT_DISPLAYED = 20;
    EMERGENCY_LIGHT = 22;
}

message TellTaleStatus {
  option (sdv.vsidl.topic) = {
    typed_name: "Telltale"
  };

  bool alert = 1;
}

enum Gear {
    P = 0;
    R = 1;
    N = 2;
    D = 3;
}

// TODO: figure out how to create topic without an enum
enum CurrentGearTopic {
    option (sdv.vsidl.is_topic) = true;
    GEAR = 0;
}

message CurrentGear {
    option (sdv.vsidl.topic) = {
        typed_name: "CurrentGearTopic"
    };

    Gear gear = 1;
}
