# Copyright 2024 Google LLC
# proto-file: system/software_defined_vehicle/core_services/orchestration/src/distributed_config/protos/service_bundle_config.proto
# proto-message: ServiceBundleConfig

instance: "instance-1"
service_bundle_name: "HarUserPreferencesServiceBundle"
package_name: "com.sdv.google.display_safety.service_bundle_apex"

state {
  instances_states {
    started: "instance-1"
  }
}
