// Copyright 2024 Google LLC

//! WARNING: DO NOT EDIT.
//! WARNING: This file is generated by VSIDL middleware code generator.
//! WARNING: Changes will be overwritten when the file is regenerated.

/// UnitType FQN
pub trait UnitType {
    /// Owning package name
    const PACKAGE: &'static str;
    /// Owning service bundle name
    const SERVICE_BUNDLE: &'static str;
    /// Type name
    const TYPENAME: &'static str;

    /// Convert the trait into a TypeName struct
    fn to_type_name() -> sdv::status::SdvResult<sdv::mw::TypeName> {
        sdv::mw::TypeName::builder()
            .package_name(Self::PACKAGE)
            .bundle_name(Self::SERVICE_BUNDLE)
            .type_name(Self::TYPENAME)
            .build()
    }
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "TirePressure";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "VehicleSpeed";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "TellTaleStatus";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "CurrentGear";
}

/// Provides access to subscriptions available to the service bundle
pub mod subscriber {

    /// Lists variants per protobuf message of every subscription available to the service bundle
    #[derive(Debug)]
    pub struct Variant<Proto> {
        _proto: std::marker::PhantomData<Proto>,
        /// Unique id of a variant
        pub id: i32,
        pub(super) service_bundle_package: &'static str,
        pub(super) service_bundle_name: &'static str,
        pub(super) service_unit: &'static str,
    }

    /// Publication-related metadata
    pub trait Metadata {
        /// Is multi-pub
        const IS_MULTIPUB: bool;
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure {
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure> {
        /// Enables access to subscription variant 'FRONT_LEFT' of 'com.sdv.google.display_safety.TirePressure'
        pub const FRONT_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FRONT_LEFT as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tire-pressure-front-left",
        };
        /// Enables access to subscription variant 'FRONT_RIGHT' of 'com.sdv.google.display_safety.TirePressure'
        pub const FRONT_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FRONT_RIGHT as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tire-pressure-front-right",
        };
        /// Enables access to subscription variant 'REAR_LEFT' of 'com.sdv.google.display_safety.TirePressure'
        pub const REAR_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::REAR_LEFT as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tire-pressure-rear-left",
        };
        /// Enables access to subscription variant 'REAR_RIGHT' of 'com.sdv.google.display_safety.TirePressure'
        pub const REAR_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::REAR_RIGHT as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tire-pressure-rear-right",
        };
        /// Enables access to subscription variant 'FIFTH_WHEEL' of 'com.sdv.google.display_safety.TirePressure'
        pub const FIFTH_WHEEL: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FIFTH_WHEEL as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tire-pressure-fifth-wheel",
        };
        /// List of all subscription variants of 'com.sdv.google.display_safety.TirePressure' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[
            Self::FRONT_LEFT,
            Self::FRONT_RIGHT,
            Self::REAR_LEFT,
            Self::REAR_RIGHT,
            Self::FIFTH_WHEEL,
        ];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed {
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed> {
        /// Enables access to subscription variant 'VEHICLE_SPEED' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const VEHICLE_SPEED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::VEHICLE_SPEED
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-vehicle-speed-vehicle-speed",
        };
        /// Enables access to subscription variant 'MAX_SPEED' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const MAX_SPEED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::MAX_SPEED
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-vehicle-speed-max-speed",
        };
        /// Enables access to subscription variant 'SPEEDLIMIT' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const SPEEDLIMIT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::SPEEDLIMIT
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-vehicle-speed-speedlimit",
        };
        /// List of all subscription variants of 'com.sdv.google.display_safety.VehicleSpeed' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] =
            &[Self::VEHICLE_SPEED, Self::MAX_SPEED, Self::SPEEDLIMIT];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus {
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus> {
        /// Enables access to subscription variant 'OIL_PRESSURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const OIL_PRESSURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::OIL_PRESSURE as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-oil-pressure",
        };
        /// Enables access to subscription variant 'ENGINE_TEMP' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ENGINE_TEMP: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ENGINE_TEMP as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-engine-temp",
        };
        /// Enables access to subscription variant 'CHECK_ENGINE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const CHECK_ENGINE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::CHECK_ENGINE as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-check-engine",
        };
        /// Enables access to subscription variant 'CHARGING_FAILURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const CHARGING_FAILURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::CHARGING_FAILURE
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-charging-failure",
        };
        /// Enables access to subscription variant 'SEATBELT_DRIVER' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SEATBELT_DRIVER: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SEATBELT_DRIVER
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-seatbelt-driver",
        };
        /// Enables access to subscription variant 'SEATBELT_PASSENGER' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SEATBELT_PASSENGER: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SEATBELT_PASSENGER
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-seatbelt-passenger",
        };
        /// Enables access to subscription variant 'LOW_TIRE_PRESSURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const LOW_TIRE_PRESSURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::LOW_TIRE_PRESSURE
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-low-tire-pressure",
        };
        /// Enables access to subscription variant 'AIRBAG' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const AIRBAG: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::AIRBAG as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-airbag",
        };
        /// Enables access to subscription variant 'ABS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ABS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ABS as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-abs",
        };
        /// Enables access to subscription variant 'BRAKE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const BRAKE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::BRAKE as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-brake",
        };
        /// Enables access to subscription variant 'TRACTION' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TRACTION: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TRACTION as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-traction",
        };
        /// Enables access to subscription variant 'FOG_LIGHTS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const FOG_LIGHTS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::FOG_LIGHTS as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-fog-lights",
        };
        /// Enables access to subscription variant 'PARK_LIGHTS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const PARK_LIGHTS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::PARK_LIGHTS as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-park-lights",
        };
        /// Enables access to subscription variant 'HIBEAM' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const HIBEAM: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::HIBEAM as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-hibeam",
        };
        /// Enables access to subscription variant 'LOWBEAM' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const LOWBEAM: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::LOWBEAM as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-lowbeam",
        };
        /// Enables access to subscription variant 'TURN_SIGNAL_LEFT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TURN_SIGNAL_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TURN_SIGNAL_LEFT
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-turn-signal-left",
        };
        /// Enables access to subscription variant 'TURN_SIGNAL_RIGHT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TURN_SIGNAL_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TURN_SIGNAL_RIGHT
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-turn-signal-right",
        };
        /// Enables access to subscription variant 'ADAS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ADAS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ADAS as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-adas",
        };
        /// Enables access to subscription variant 'MAX_SPEED_DISPLAYED' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const MAX_SPEED_DISPLAYED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::MAX_SPEED_DISPLAYED
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-max-speed-displayed",
        };
        /// Enables access to subscription variant 'SPEED_LIMIT_DISPLAYED' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SPEED_LIMIT_DISPLAYED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SPEED_LIMIT_DISPLAYED
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-speed-limit-displayed",
        };
        /// Enables access to subscription variant 'EMERGENCY_LIGHT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const EMERGENCY_LIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::EMERGENCY_LIGHT
                as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-tell-tale-status-emergency-light",
        };
        /// List of all subscription variants of 'com.sdv.google.display_safety.TellTaleStatus' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[
            Self::OIL_PRESSURE,
            Self::ENGINE_TEMP,
            Self::CHECK_ENGINE,
            Self::CHARGING_FAILURE,
            Self::SEATBELT_DRIVER,
            Self::SEATBELT_PASSENGER,
            Self::LOW_TIRE_PRESSURE,
            Self::AIRBAG,
            Self::ABS,
            Self::BRAKE,
            Self::TRACTION,
            Self::FOG_LIGHTS,
            Self::PARK_LIGHTS,
            Self::HIBEAM,
            Self::LOWBEAM,
            Self::TURN_SIGNAL_LEFT,
            Self::TURN_SIGNAL_RIGHT,
            Self::ADAS,
            Self::MAX_SPEED_DISPLAYED,
            Self::SPEED_LIMIT_DISPLAYED,
            Self::EMERGENCY_LIGHT,
        ];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear {
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear> {
        /// Enables access to subscription variant 'UNIQUE' of 'com.sdv.google.display_safety.CurrentGear'
        pub const UNIQUE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: vsidl_v1::annotations::UniqueInstance::UNIQUE as i32,
            service_bundle_package: "com.sdv.google.display_safety",
            service_bundle_name: "HarSdvVehicleDataPublisher",
            service_unit: "com-sdv-google-display-safety-current-gear-unique",
        };
        /// List of all subscription variants of 'com.sdv.google.display_safety.CurrentGear' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[Self::UNIQUE];
    }
}

/// Service bundle
pub struct HarSdvServiceBundle {
    comms: std::sync::Arc<dyn sdv::mw::Communicate>,
}

impl HarSdvServiceBundle {
    /// Creates a new instance of the service bundle
    pub async fn new(
        comms: std::sync::Arc<dyn sdv::mw::Communicate>,
    ) -> sdv::status::SdvResult<Self> {
        let service = Self { comms: comms.clone() };
        Ok(service)
    }

    /// Creates a new subscriber
    pub async fn create_subscriber<
        M: ::protobuf::Message + subscriber::Metadata + UnitType + 'static,
    >(
        &mut self,
        variant: &subscriber::Variant<M>,
        options: &sdv::mw::SubscribeOptions,
    ) -> sdv::status::SdvResult<sdv::mw::Subscriber<M>> {
        let subscribe_handle = match M::IS_MULTIPUB {
            // For single-pub, subscribe to a specific publication.
            false => {
                let publication = self.find_publication(variant).await?;
                publication.subscribe(options).await?
            }
            // For multi-pub, subscribe to a message type.
            true => self.comms.subscribe_by_type(&M::to_type_name()?, options).await?,
        };
        Ok(sdv::mw::Subscriber::<M>::new(subscribe_handle))
    }

    /// Creates a new observer
    pub async fn create_observer<
        M: ::protobuf::Message + subscriber::Metadata + UnitType + 'static,
    >(
        &mut self,
        variant: &subscriber::Variant<M>,
        options: &sdv::mw::SubscribeOptions,
    ) -> sdv::status::SdvResult<
        std::pin::Pin<
            Box<dyn futures::stream::Stream<Item = sdv::status::SdvResult<Vec<M>>> + Send>,
        >,
    > {
        let byte_buffer_stream = match M::IS_MULTIPUB {
            // For single-pub, observe a specific publication.
            false => {
                let publication = self.find_publication(variant).await?;
                publication.observe(options).await?
            }
            // For multi-pub, observe a message type.
            true => self.comms.observe_by_type(&M::to_type_name()?, options).await?,
        };
        Ok(sdv::mw::observe::<M>(byte_buffer_stream))
    }

    /// Creates a new history
    pub async fn create_history<M: ::protobuf::Message + subscriber::Metadata + 'static>(
        &mut self,
        variant: &subscriber::Variant<M>,
        options: &sdv::mw::SubscribeOptions,
    ) -> sdv::status::SdvResult<sdv::mw::History<M>> {
        if M::IS_MULTIPUB {
            Err(sdv::status::SdvStatus::with_message(
                sdv::status::SdvStatusCode::Unimplemented,
                "History is not supported for Multipub variants.",
            ))
        } else {
            let publication = self.find_publication(variant).await?;
            Ok(sdv::mw::History::<M>::new(publication.create_history(options).await?))
        }
    }

    /// Creates a new instant reader
    pub async fn create_instant_reader<M: ::protobuf::Message + subscriber::Metadata + 'static>(
        &mut self,
        variant: &subscriber::Variant<M>,
    ) -> sdv::status::SdvResult<sdv::mw::InstantReader<M>> {
        if M::IS_MULTIPUB {
            Err(sdv::status::SdvStatus::with_message(
                sdv::status::SdvStatusCode::Unimplemented,
                "Instant Read is not supported for Multipub variants.",
            ))
        } else {
            let publication = self.find_publication(variant).await?;
            Ok(sdv::mw::InstantReader::<M>::new(publication.create_instant_read()))
        }
    }

    async fn find_publication<M: ::protobuf::Message + 'static>(
        &mut self,
        variant: &subscriber::Variant<M>,
    ) -> sdv::status::SdvResult<std::sync::Arc<dyn sdv::mw::Publication>> {
        self.comms
            .find_publication(&sdv::mw::UnitQuery::Name(
                sdv::mw::UnitName::builder()
                    .vm_name(String::new())
                    .package_name(variant.service_bundle_package)
                    .bundle_name(variant.service_bundle_name)
                    .service_unit_name(variant.service_unit)
                    .build()?,
            ))
            .await
    }

    /// Creates a new event stream
    pub async fn create_registration_event_stream<M: ::protobuf::Message + 'static>(
        &mut self,
        variant: &subscriber::Variant<M>,
    ) -> sdv::status::SdvResult<
        std::pin::Pin<Box<dyn futures::Stream<Item = sdv::mw::Availability> + Send>>,
    > {
        self.comms
            .create_registration_event_stream(&sdv::mw::UnitQuery::Name(
                sdv::mw::UnitName::builder()
                    .vm_name(String::new())
                    .package_name(variant.service_bundle_package)
                    .bundle_name(variant.service_bundle_name)
                    .service_unit_name(variant.service_unit)
                    .build()?,
            ))
            .await
    }
}
