# Copyright 2024 Google LLC
# proto-file: //system/software_defined_vehicle/core_services/service_authz/proto/sdv/authz/policy/acl_policy.proto
# proto-message: AclPolicy

# ACL policies for HarSdvServiceBundle.

acls {
    name: "HarSdvService"
    include: "com.sdv.google.display_safety.*"
}

unit_types {
  name: "HarSdvServiceBundle"
  acl_names: "HarSdvService"
}

unit_types {
  name: "VehicleSpeed"
  acl_names: "HarSdvService"
}

unit_types {
  name: "TirePressure"
  acl_names: "HarSdvService"
}

unit_types {
  name: "TellTaleStatus"
  acl_names: "HarSdvService"
}

unit_types {
  name: "CurrentGear"
  acl_names: "HarSdvService"
}

unit_types {
  name: "DriverUIService"
  acl_names: "HarSdvService"
}
