// Copyright 2024 Google LLC

//! WARNING: DO NOT EDIT.
//! WARNING: This file is generated by VSIDL middleware code generator.
//! WARNING: Changes will be overwritten when the file is regenerated.

/// UnitType FQN
pub trait UnitType {
    /// Owning package name
    const PACKAGE: &'static str;
    /// Owning service bundle name
    const SERVICE_BUNDLE: &'static str;
    /// Type name
    const TYPENAME: &'static str;

    /// Convert the trait into a TypeName struct
    fn to_type_name() -> sdv::status::SdvResult<sdv::mw::TypeName> {
        sdv::mw::TypeName::builder()
            .package_name(Self::PACKAGE)
            .bundle_name(Self::SERVICE_BUNDLE)
            .type_name(Self::TYPENAME)
            .build()
    }
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "TirePressure";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "VehicleSpeed";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "TellTaleStatus";
}

impl UnitType for oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear {
    const PACKAGE: &'static str = "com.sdv.google.display_safety";
    const SERVICE_BUNDLE: &'static str = "HarSdvServiceBundle";
    const TYPENAME: &'static str = "CurrentGear";
}

/// Provides access to publications available to the service bundle
pub mod publisher {

    /// Lists variants per protobuf message of every publication available to the service bundle
    #[derive(Debug)]
    pub struct Variant<Proto> {
        _proto: std::marker::PhantomData<Proto>,
        /// Unique id of a variant
        pub id: i32,
        pub(super) service_unit: &'static str,
    }

    pub(super) trait Metadata {
        const MESSAGE_SIZE: u32;
        const MESSAGE_COUNT: u32;
        const IS_MULTIPUB: bool;
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure {
        const MESSAGE_SIZE: u32 = 11;
        const MESSAGE_COUNT: u32 = 8;
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure> {
        /// Publication variant 'FRONT_LEFT' of 'com.sdv.google.display_safety.TirePressure'
        pub const FRONT_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FRONT_LEFT as i32,
            service_unit: "com-sdv-google-display-safety-tire-pressure-front-left",
        };
        /// Publication variant 'FRONT_RIGHT' of 'com.sdv.google.display_safety.TirePressure'
        pub const FRONT_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FRONT_RIGHT as i32,
            service_unit: "com-sdv-google-display-safety-tire-pressure-front-right",
        };
        /// Publication variant 'REAR_LEFT' of 'com.sdv.google.display_safety.TirePressure'
        pub const REAR_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::REAR_LEFT as i32,
            service_unit: "com-sdv-google-display-safety-tire-pressure-rear-left",
        };
        /// Publication variant 'REAR_RIGHT' of 'com.sdv.google.display_safety.TirePressure'
        pub const REAR_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::REAR_RIGHT as i32,
            service_unit: "com-sdv-google-display-safety-tire-pressure-rear-right",
        };
        /// Publication variant 'FIFTH_WHEEL' of 'com.sdv.google.display_safety.TirePressure'
        pub const FIFTH_WHEEL: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicle_tire::Location::FIFTH_WHEEL as i32,
            service_unit: "com-sdv-google-display-safety-tire-pressure-fifth-wheel",
        };
        /// List of all publication variants of 'com.sdv.google.display_safety.TirePressure' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[
            Self::FRONT_LEFT,
            Self::FRONT_RIGHT,
            Self::REAR_LEFT,
            Self::REAR_RIGHT,
            Self::FIFTH_WHEEL,
        ];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed {
        const MESSAGE_SIZE: u32 = 11;
        const MESSAGE_COUNT: u32 = 8;
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed> {
        /// Publication variant 'VEHICLE_SPEED' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const VEHICLE_SPEED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::VEHICLE_SPEED
                as i32,
            service_unit: "com-sdv-google-display-safety-vehicle-speed-vehicle-speed",
        };
        /// Publication variant 'MAX_SPEED' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const MAX_SPEED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::MAX_SPEED
                as i32,
            service_unit: "com-sdv-google-display-safety-vehicle-speed-max-speed",
        };
        /// Publication variant 'SPEEDLIMIT' of 'com.sdv.google.display_safety.VehicleSpeed'
        pub const SPEEDLIMIT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeedTopic::SPEEDLIMIT
                as i32,
            service_unit: "com-sdv-google-display-safety-vehicle-speed-speedlimit",
        };
        /// List of all publication variants of 'com.sdv.google.display_safety.VehicleSpeed' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] =
            &[Self::VEHICLE_SPEED, Self::MAX_SPEED, Self::SPEEDLIMIT];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus {
        const MESSAGE_SIZE: u32 = 11;
        const MESSAGE_COUNT: u32 = 8;
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus> {
        /// Publication variant 'OIL_PRESSURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const OIL_PRESSURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::OIL_PRESSURE as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-oil-pressure",
        };
        /// Publication variant 'ENGINE_TEMP' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ENGINE_TEMP: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ENGINE_TEMP as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-engine-temp",
        };
        /// Publication variant 'CHECK_ENGINE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const CHECK_ENGINE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::CHECK_ENGINE as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-check-engine",
        };
        /// Publication variant 'CHARGING_FAILURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const CHARGING_FAILURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::CHARGING_FAILURE
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-charging-failure",
        };
        /// Publication variant 'SEATBELT_DRIVER' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SEATBELT_DRIVER: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SEATBELT_DRIVER
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-seatbelt-driver",
        };
        /// Publication variant 'SEATBELT_PASSENGER' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SEATBELT_PASSENGER: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SEATBELT_PASSENGER
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-seatbelt-passenger",
        };
        /// Publication variant 'LOW_TIRE_PRESSURE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const LOW_TIRE_PRESSURE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::LOW_TIRE_PRESSURE
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-low-tire-pressure",
        };
        /// Publication variant 'AIRBAG' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const AIRBAG: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::AIRBAG as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-airbag",
        };
        /// Publication variant 'ABS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ABS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ABS as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-abs",
        };
        /// Publication variant 'BRAKE' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const BRAKE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::BRAKE as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-brake",
        };
        /// Publication variant 'TRACTION' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TRACTION: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TRACTION as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-traction",
        };
        /// Publication variant 'FOG_LIGHTS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const FOG_LIGHTS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::FOG_LIGHTS as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-fog-lights",
        };
        /// Publication variant 'PARK_LIGHTS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const PARK_LIGHTS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::PARK_LIGHTS as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-park-lights",
        };
        /// Publication variant 'HIBEAM' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const HIBEAM: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::HIBEAM as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-hibeam",
        };
        /// Publication variant 'LOWBEAM' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const LOWBEAM: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::LOWBEAM as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-lowbeam",
        };
        /// Publication variant 'TURN_SIGNAL_LEFT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TURN_SIGNAL_LEFT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TURN_SIGNAL_LEFT
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-turn-signal-left",
        };
        /// Publication variant 'TURN_SIGNAL_RIGHT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const TURN_SIGNAL_RIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::TURN_SIGNAL_RIGHT
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-turn-signal-right",
        };
        /// Publication variant 'ADAS' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const ADAS: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::ADAS as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-adas",
        };
        /// Publication variant 'MAX_SPEED_DISPLAYED' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const MAX_SPEED_DISPLAYED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::MAX_SPEED_DISPLAYED
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-max-speed-displayed",
        };
        /// Publication variant 'SPEED_LIMIT_DISPLAYED' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const SPEED_LIMIT_DISPLAYED: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::SPEED_LIMIT_DISPLAYED
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-speed-limit-displayed",
        };
        /// Publication variant 'EMERGENCY_LIGHT' of 'com.sdv.google.display_safety.TellTaleStatus'
        pub const EMERGENCY_LIGHT: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: oem_harry_vehicle_messages_catalog_v1::vehicledata::Telltale::EMERGENCY_LIGHT
                as i32,
            service_unit: "com-sdv-google-display-safety-tell-tale-status-emergency-light",
        };
        /// List of all publication variants of 'com.sdv.google.display_safety.TellTaleStatus' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[
            Self::OIL_PRESSURE,
            Self::ENGINE_TEMP,
            Self::CHECK_ENGINE,
            Self::CHARGING_FAILURE,
            Self::SEATBELT_DRIVER,
            Self::SEATBELT_PASSENGER,
            Self::LOW_TIRE_PRESSURE,
            Self::AIRBAG,
            Self::ABS,
            Self::BRAKE,
            Self::TRACTION,
            Self::FOG_LIGHTS,
            Self::PARK_LIGHTS,
            Self::HIBEAM,
            Self::LOWBEAM,
            Self::TURN_SIGNAL_LEFT,
            Self::TURN_SIGNAL_RIGHT,
            Self::ADAS,
            Self::MAX_SPEED_DISPLAYED,
            Self::SPEED_LIMIT_DISPLAYED,
            Self::EMERGENCY_LIGHT,
        ];
    }

    impl Metadata for oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear {
        const MESSAGE_SIZE: u32 = 11;
        const MESSAGE_COUNT: u32 = 8;
        const IS_MULTIPUB: bool = false;
    }

    impl Variant<oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear> {
        /// Publication variant 'UNIQUE' of 'com.sdv.google.display_safety.CurrentGear'
        pub const UNIQUE: &Self = &Self {
            _proto: std::marker::PhantomData,
            id: vsidl_v1::annotations::UniqueInstance::UNIQUE as i32,
            service_unit: "com-sdv-google-display-safety-current-gear-unique",
        };
        /// List of all publication variants of 'com.sdv.google.display_safety.CurrentGear' available to the service bundle
        pub const ALL_VARIANTS: &'static [&'static Self] = &[Self::UNIQUE];
    }
}

/// Service bundle
pub struct HarSdvVehicleDataPublisher {
    comms: std::sync::Arc<dyn sdv::mw::Communicate>,
    publishers: std::collections::HashMap<(std::any::TypeId, i32), Box<dyn std::any::Any + Send>>,
}

impl HarSdvVehicleDataPublisher {
    /// Creates a new instance of the service bundle
    pub async fn new(
        comms: std::sync::Arc<dyn sdv::mw::Communicate>,
    ) -> sdv::status::SdvResult<Self> {
        let mut service =
            Self { comms: comms.clone(), publishers: std::collections::HashMap::new() };
        service
            .fill_publication_variants(
                publisher::Variant::<
                    oem_harry_vehicle_messages_catalog_v1::vehicle_tire::TirePressure,
                >::ALL_VARIANTS,
            )
            .await?;
        service
            .fill_publication_variants(
                publisher::Variant::<
                    oem_harry_vehicle_messages_catalog_v1::vehicledata::VehicleSpeed,
                >::ALL_VARIANTS,
            )
            .await?;
        service
            .fill_publication_variants(
                publisher::Variant::<
                    oem_harry_vehicle_messages_catalog_v1::vehicledata::TellTaleStatus,
                >::ALL_VARIANTS,
            )
            .await?;
        service.fill_publication_variants(publisher::Variant::<oem_harry_vehicle_messages_catalog_v1::vehicledata::CurrentGear>::ALL_VARIANTS).await?;
        Ok(service)
    }

    /// Take the ownership of the publisher object
    /// Will return None if called more than once per publisher variant
    pub fn take_publisher<M: protobuf::Message + 'static>(
        &mut self,
        variant: &publisher::Variant<M>,
    ) -> Option<sdv::mw::Publisher<M>> {
        Some(
            *self
                .publishers
                .remove(&(std::any::TypeId::of::<M>(), variant.id))?
                .downcast::<sdv::mw::Publisher<M>>()
                .unwrap(),
        )
    }

    async fn fill_publication_variants<
        M: UnitType + publisher::Metadata + ::protobuf::Message + 'static,
    >(
        &mut self,
        variants: &[&publisher::Variant<M>],
    ) -> sdv::status::SdvResult<()> {
        for variant in variants {
            let publish_handle = self
                .comms
                .create_publish(
                    &sdv::mw::PublisherAttributes::builder()
                        .publication_name(variant.service_unit)
                        .type_name(
                            sdv::mw::TypeName::builder()
                                .package_name(M::PACKAGE)
                                .bundle_name(M::SERVICE_BUNDLE)
                                .type_name(M::TYPENAME)
                                .build()?,
                        )
                        .metadata(
                            sdv::mw::PublisherMetadata::builder()
                                .message_size(M::MESSAGE_SIZE)
                                .message_count(M::MESSAGE_COUNT)
                                .is_multipub(M::IS_MULTIPUB)
                                .build()?,
                        )
                        .build()?,
                )
                .await?;
            self.publishers.insert(
                (std::any::TypeId::of::<M>(), variant.id),
                Box::new(sdv::mw::Publisher::<M>::new(publish_handle)),
            );
        }
        Ok(())
    }
}
